export default {
  CREATE_CLUSTER: "CREATE_CLUSTER",
  CREATE_CLUSTER_FAILED: "CREATE_CLUSTER_FAILED",

  MENU_SELECT: "MENU_SELECT",
  GET_LOOKUP_OPTIONS_DATA: "GET_LOOKUP_OPTIONS_DATA",
  GET_LOOKUP_OPTIONS_DATA_FAILED: "GET_LOOKUP_OPTIONS_DATA_FAILED",

  CREATE_SECURITY_SUCCESS: "CREATE_SECURITY_SUCCESS",
  CREATE_SECURITY_FAILED: "CREATE_SECURITY_FAILED",

  CREATE_NAMESPACE_SUCCESS: "CREATE_NAMESPACE_SUCCESS",
  CREATE_NAMESPACE_FAILED: "CREATE_NAMESPACE_FAILED",

  GET_CREDENTIALS_SUCCESS: "GET_CREDENTIALS",
  GET_CREDENTIALS_FAILED: "GET_CREDENTIALS_FAILED",

  CREDENTIAL_DELETED: "CREDENTIAL_DELETED",
  CREDENTIAL_DELETE_FAILED: "CREDENTIAL_DELETE_FAILED",
};
