export default {
  CREATE_CLUSTER_SUCCESS: "CREATE_CLUSTER_SUCCESS",
  CREATE_CLUSTER_FAILED: "CREATE_CLUSTER_FAILED",

  MENU_SELECTED: "MENU_SELECTED",
  GET_LOOKUP_OPTIONS_DATA_SUCCESS: "GET_LOOKUP_OPTIONS_DATA_SUCCESS",
  GET_LOOKUP_OPTIONS_DATA_FAILED: "GET_LOOKUP_OPTIONS_DATA_FAILED",

  CREATE_SECURITY_SUCCESS: "CREATE_SECURITY_SUCCESS",
  CREATE_SECURITY_FAILED: "CREATE_SECURITY_FAILED",

  CREATE_NAMESPACE_SUCCESS: "CREATE_NAMESPACE_SUCCESS",
  CREATE_NAMESPACE_FAILED: "CREATE_NAMESPACE_FAILED",

  GET_CREDENTIALS_SUCCESS: "GET_CREDENTIALS_SUCCESS",
  DELETE_CREDENTIAL_SUCCESS: "DELETE_CREDENTIAL_SUCCESS",
};
